name: Deploy Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/lumina-api:${{ github.sha }}
          docker build -t $IMAGE_NAME .

      - name: Push Docker Image
        if: github.event_name == 'push'
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/lumina-api:${{ github.sha }}
          docker push $IMAGE_NAME

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: SSH and Update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Authenticate with GHCR
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Pull latest image
            docker pull ghcr.io/${{ github.repository_owner }}/lumina-api:${{ github.sha }}
            export IMAGE=ghcr.io/${{ github.repository_owner }}/lumina-api:${{ github.sha }}
            # Update standard container
            # Assuming docker-compose.yml is in the root directory
            cd /home/ubuntu/lumina && \
            docker compose up -d --no-deps lumina-api
            docker image prune -f --filter "dangling=true"
